; EnemyDefault.inc : エネミーの初期値
;


; マクロの定義
;

; 外部関数宣言
;

; 外部変数宣言
;

    .globl  _enemyDefaultNull
    .globl  _enemyDefaultBat
    .globl  _enemyDefaultGoblin
    .globl  _enemyDefaultRogue
    .globl  _enemyDefaultGargoyle
    .globl  _enemyDefaultReaper
    .globl  _enemyDefaultLizard
    .globl  _enemyDefaultMage
    .globl  _enemyDefaultSnake
    .globl  _enemyDefaultGhoul
    .globl  _enemyDefaultDaemon
    .globl  _enemyDefaultSquid
    .globl  _enemyDefaultGazer
    .globl  _enemyDefaultSpider
    .globl  _enemyDefaultRat
    .globl  _enemyDefaultMimic
    .globl  _enemyDefaultSlime
    .globl  _enemyDefaultGolem
    .globl  _enemyDefaultGhost
    .globl  _enemyDefaultLich
    .globl  _enemyDefaultPhantom
    .globl  _enemyDefaultCyclops
    .globl  _enemyDefaultZorn
    .globl  _enemyDefaultShadow
    .globl  _enemyDefaultDragon
    .globl  _enemyDefaultCrystal
    .globl  _enemyDefaultGate
    .globl  _enemyDefaultMagic
